# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180703_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='商品封面图'),
        ),
    ]
