# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180703_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=30, verbose_name='商品名'),
        ),
    ]
