# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180702_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='goods_nums',
            new_name='nums',
        ),
    ]
