# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='未命名', max_length=30, null=True, verbose_name='姓名'),
        ),
    ]
