# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20180702_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(blank=True, help_text='上传的文件', null=True, upload_to='', verbose_name='上传的文件'),
        ),
    ]
